import assert from 'node:assert/strict';
import { generateText, transcribeAudio } from '../local-ai-service.ts';
import { parseWaterCommand, validateReply } from '../action-validation.ts';
const state={profile:{goals:{waterLitersDaily:3}},waterLogs:[{date:'2026-10-05',amountMl:1500}],tasks:[{id:'t1',title:'DBMS assignment'},{id:'t2',title:'DBMS assignment review'}]};
const a=validateReply(parseWaterCommand('I drank 1.5 liters of water'),state,'2026-10-05');assert.match(a.replyText,/1.5 L remaining/);
const b=validateReply(parseWaterCommand('I drank another 500 ml'),state,'2026-10-05');assert.match(b.replyText,/total is 2 L/);assert.match(b.replyText,/1 L remaining/);
assert.equal(parseWaterCommand('How much water is 500 ml?'),null);
assert.equal(parseWaterCommand('I drank 500 ml yesterday'),null);
assert.equal(validateReply({replyText:'Done',proposedAction:{actionType:'record_water',payload:{amountMl:-1,mode:'add'}}},state,'2026-10-05').proposedAction,null);
assert.equal(validateReply({replyText:'Done',proposedAction:{actionType:'complete_task',payload:{taskTitle:'DBMS'}}},state,'2026-10-05').proposedAction,null);
const task=validateReply({replyText:'Done',proposedAction:{actionType:'complete_task',payload:{id:'t1'}}},state,'2026-10-05');assert.equal(task.proposedAction.payload.id,'t1');assert.equal(task.proposedAction.requiresConfirmation,true);
assert.equal(validateReply({replyText:'Done',proposedAction:{actionType:'update_goals',payload:{waterLitersDaily:4}}},state,'2026-10-05').proposedAction.requiresConfirmation,true);
let requests:any[]=[];
globalThis.fetch=async (url:any,options:any)=>{requests.push({url,options});return Response.json(url.endsWith('/transcribe')?{transcript:'నేను నీళ్లు తాగాను'}:{message:{content:'{"replyText":"Hello","proposedAction":null}'}});};
await generateText('Log activity',{json:true,system:'LifeForge only'});assert.equal(JSON.parse(requests[0].options.body).format,'json');assert.equal(requests[0].options.headers.Authorization,undefined);assert.match(requests[0].url,/127.0.0.1/);
await transcribeAudio('AAAA','audio/webm');assert.match(requests[1].url,/8001\/transcribe/);
await assert.rejects(()=>generateText('Inspect',{image:{data:'AAAA',mimeType:'image/jpeg'}}),/vision model/);
process.env.OLLAMA_URL='https://api.openai.com';await assert.rejects(()=>generateText('x'),/localhost/);delete process.env.OLLAMA_URL;
globalThis.fetch=async()=>{throw new Error('offline');};await assert.rejects(()=>generateText('x'),/Ollama is not running/);
console.log('PASS: water math, question/history exclusion, validation, ambiguous tasks, confirmation, local JSON chat/speech and service errors');
