import { LifeForgeState } from '../types/lifeforge';

export function getTodayDateStr(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

export function getPastDateStr(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

export function createInitialDemoState(): LifeForgeState {
  const today = getTodayDateStr();
  const yesterday = getPastDateStr(1);
  const twoDaysAgo = getPastDateStr(2);
  const threeDaysAgo = getPastDateStr(3);
  const fourDaysAgo = getPastDateStr(4);
  const fiveDaysAgo = getPastDateStr(5);
  const sixDaysAgo = getPastDateStr(6);
  const sevenDaysAgo = getPastDateStr(7);

  return {
    profile: {
      id: 'demo-user-1',
      name: 'Himavanth Sairam',
      email: 'himavanth@example.com',
      isGuest: true,
      goals: {
        studyHoursDaily: 3.0,
        waterLitersDaily: 3.0,
        sleepHoursDaily: 8.0,
        socialMediaMaxMinutesDaily: 120, // 2 hours
        exerciseDaysPerWeek: 5,
        calorieTargetDaily: 2200,
        proteinTargetDaily: 110,
      },
      foodPreferences: 'Balanced homemade meals, egg & chicken protein sources',
      preferredLanguage: 'auto',
      motivationStyle: 'honest-evidence',
      joinedDate: sevenDaysAgo,
    },
    tasks: [
      {
        id: 't-1',
        title: 'Finish DBMS Assignment (Indexing & B+ Trees)',
        category: 'Study',
        dueDate: today,
        dueTime: '17:00',
        priority: 'high',
        isRecurring: false,
        completed: false,
      },
      {
        id: 't-2',
        title: 'Revise Operating Systems Process Scheduling',
        category: 'Study',
        dueDate: today,
        dueTime: '19:30',
        priority: 'medium',
        isRecurring: false,
        completed: true,
        completedAt: `${today}T19:15:00Z`,
      },
      {
        id: 't-3',
        title: 'Evening Upper Body Workout (Bench Press & Core)',
        category: 'Exercise',
        dueDate: today,
        dueTime: '18:00',
        priority: 'high',
        isRecurring: true,
        recurringType: 'daily',
        completed: true,
        completedAt: `${today}T18:50:00Z`,
      },
      {
        id: 't-4',
        title: 'College Lab Record Submission',
        category: 'Commitment',
        dueDate: today,
        dueTime: '14:00',
        priority: 'high',
        isRecurring: false,
        completed: true,
        completedAt: `${today}T13:30:00Z`,
      },
      {
        id: 't-5',
        title: 'Drink remaining 400ml water before sleep',
        category: 'Health',
        dueDate: today,
        dueTime: '22:00',
        priority: 'low',
        isRecurring: true,
        recurringType: 'daily',
        completed: false,
      },
      {
        id: 't-6',
        title: 'Read 20 pages of "Atomic Habits"',
        category: 'Custom',
        dueDate: today,
        dueTime: '21:30',
        priority: 'medium',
        isRecurring: true,
        recurringType: 'daily',
        completed: true,
      },
      {
        id: 't-7',
        title: 'Prepare Computer Networks Presentation slides',
        category: 'Study',
        dueDate: today,
        dueTime: '22:30',
        priority: 'high',
        isRecurring: false,
        completed: false,
      },
      {
        id: 't-8',
        title: 'No screen time 30 mins before sleep',
        category: 'Health',
        dueDate: today,
        dueTime: '23:00',
        priority: 'medium',
        isRecurring: true,
        recurringType: 'daily',
        completed: false,
      },
      {
        id: 't-9',
        title: 'Review System Design notes',
        category: 'Study',
        dueDate: yesterday,
        dueTime: '20:00',
        priority: 'medium',
        isRecurring: false,
        completed: true,
      },
      {
        id: 't-10',
        title: 'Hydration check - afternoon milestone',
        category: 'Health',
        dueDate: yesterday,
        dueTime: '15:00',
        priority: 'low',
        isRecurring: true,
        recurringType: 'daily',
        completed: true,
      },
    ],
    studyRecords: [
      {
        id: 's-1',
        subject: 'DBMS',
        topic: 'Relational Algebra & Normalization',
        durationHours: 2.5,
        date: today,
        understandingScore: 4,
        examConfidence: 'high',
        improvementFromLast: 'Mastered 3NF and BCNF decomposition rules with minimal errors.',
        notes: 'Solved 10 university past exam questions.',
      },
      {
        id: 's-2',
        subject: 'Operating Systems',
        topic: 'Process Scheduling (Round Robin & SJF)',
        durationHours: 1.5,
        date: yesterday,
        understandingScore: 4,
        examConfidence: 'medium',
        improvementFromLast: 'Understood preemptive vs non-preemptive calculation algorithms.',
        notes: 'Calculated average waiting time formulas.',
      },
      {
        id: 's-3',
        subject: 'Computer Networks',
        topic: 'TCP/IP Handshake & Sliding Window Protocol',
        durationHours: 2.0,
        date: twoDaysAgo,
        understandingScore: 3,
        examConfidence: 'medium',
        improvementFromLast: 'Grasped three-way SYN/ACK sequence flow.',
        notes: 'Need to review congestion control algorithms.',
      },
      {
        id: 's-4',
        subject: 'DBMS',
        topic: 'SQL Joins & Group By Queries',
        durationHours: 2.0,
        date: threeDaysAgo,
        understandingScore: 5,
        examConfidence: 'high',
        improvementFromLast: 'Fast query execution practice.',
      },
      {
        id: 's-5',
        subject: 'Data Structures',
        topic: 'AVL Trees & Rotations',
        durationHours: 1.5,
        date: fourDaysAgo,
        understandingScore: 3,
        examConfidence: 'low',
        improvementFromLast: 'Understood left-right double rotations.',
      },
      {
        id: 's-6',
        subject: 'Operating Systems',
        topic: 'Deadlock Detection & Banker Algorithm',
        durationHours: 2.0,
        date: fiveDaysAgo,
        understandingScore: 4,
        examConfidence: 'high',
      },
    ],
    exerciseRecords: [
      {
        id: 'e-1',
        activity: 'Bench Press & Chest Workout',
        durationMinutes: 45,
        details: 'Bench Press 3 sets of 10 @ 60kg, Incline Dumbbell 3x12, Push-ups 3x20',
        intensity: 'high',
        date: today,
        notes: 'Felt strong, clean form on bench press.',
      },
      {
        id: 'e-2',
        activity: 'Outdoor Running',
        durationMinutes: 25,
        details: '3.2 km run at 5:40/km pace',
        intensity: 'moderate',
        date: yesterday,
        notes: 'Evening run around campus track.',
      },
      {
        id: 'e-3',
        activity: 'Back & Biceps Gym Session',
        durationMinutes: 50,
        details: 'Lat Pulldowns 4x12 @ 55kg, Barbell Rows 3x10, Hammer Curls 3x12',
        intensity: 'high',
        date: twoDaysAgo,
      },
      {
        id: 'e-4',
        activity: 'HIIT & Core Conditioning',
        durationMinutes: 30,
        details: 'Planks 3x60s, Mountain Climbers, Jump Rope 500 skips',
        intensity: 'high',
        date: fourDaysAgo,
      },
      {
        id: 'e-5',
        activity: 'Evening Brisk Walk',
        durationMinutes: 35,
        details: '3.5 km walk post dinner',
        intensity: 'light',
        date: fiveDaysAgo,
      },
    ],
    nutritionMeals: [
      {
        id: 'n-1',
        mealType: 'Breakfast',
        foods: ['4 Steamed Idlis', 'Sambar', 'Coconut Chutney', 'Filter Coffee'],
        calories: 380,
        protein: 12,
        carbs: 68,
        fat: 6,
        time: '08:15',
        date: today,
        aiEstimated: false,
        portionNotes: 'Standard homemade portions',
      },
      {
        id: 'n-2',
        mealType: 'Lunch',
        foods: ['Steamed Rice (1.5 cups)', 'Chicken Curry (150g)', 'Dal Tadka', 'Cucumber salad'],
        calories: 680,
        protein: 42,
        carbs: 85,
        fat: 16,
        time: '13:00',
        date: today,
        aiEstimated: true,
        portionNotes: 'AI estimated from meal composition',
      },
      {
        id: 'n-3',
        mealType: 'Snack',
        foods: ['Roasted Peanuts (40g)', 'Green Tea'],
        calories: 230,
        protein: 10,
        carbs: 8,
        fat: 18,
        time: '17:15',
        date: today,
        aiEstimated: false,
      },
      {
        id: 'n-4',
        mealType: 'Dinner',
        foods: ['2 Whole Wheat Rotis', 'Paneer Bhurji', 'Curd'],
        calories: 520,
        protein: 26,
        carbs: 48,
        fat: 22,
        time: '20:30',
        date: yesterday,
        aiEstimated: false,
      },
    ],
    waterLogs: [
      // Yesterday and historical records for comparison calculations:
      { id: 'w-6', amountMl: 2800, time: '21:00', date: yesterday },
      { id: 'w-7', amountMl: 3000, time: '21:00', date: twoDaysAgo },
      { id: 'w-8', amountMl: 2600, time: '21:00', date: threeDaysAgo },
    ],
    sleepRecords: [
      {
        id: 'sl-1',
        sleepTime: '23:15',
        wakeTime: '07:00',
        durationHours: 7.75, // 7h 45m
        targetHours: 8.0,
        quality: 'good',
        date: today,
        notes: 'Woke up refreshed, minimal midnight wakeups.',
      },
      {
        id: 'sl-2',
        sleepTime: '23:45',
        wakeTime: '06:45',
        durationHours: 7.0,
        targetHours: 8.0,
        quality: 'fair',
        date: yesterday,
      },
      {
        id: 'sl-3',
        sleepTime: '23:00',
        wakeTime: '07:30',
        durationHours: 8.5,
        targetHours: 8.0,
        quality: 'great',
        date: twoDaysAgo,
      },
      {
        id: 'sl-4',
        sleepTime: '00:15',
        wakeTime: '07:00',
        durationHours: 6.75,
        targetHours: 8.0,
        quality: 'poor',
        date: threeDaysAgo,
      },
      {
        id: 'sl-5',
        sleepTime: '23:30',
        wakeTime: '07:15',
        durationHours: 7.75,
        targetHours: 8.0,
        quality: 'good',
        date: fourDaysAgo,
      },
    ],
    socialMediaLogs: [
      {
        id: 'sm-1',
        durationMinutes: 100, // 1h 40m
        platform: 'YouTube & Instagram',
        morningRestrictedViolated: false,
        nightRestrictedViolated: false,
        date: today,
        notes: 'Mainly educational tech videos and brief chat.',
      },
      {
        id: 'sm-2',
        durationMinutes: 130, // 2h 10m
        platform: 'Instagram Reels',
        morningRestrictedViolated: false,
        nightRestrictedViolated: true,
        date: yesterday,
        notes: 'Over the 2-hour limit by 10 minutes at night.',
      },
      {
        id: 'sm-3',
        durationMinutes: 180, // 3h
        platform: 'Reddit & YouTube',
        morningRestrictedViolated: true,
        nightRestrictedViolated: true,
        date: twoDaysAgo,
      },
      {
        id: 'sm-4',
        durationMinutes: 90,
        platform: 'WhatsApp & LinkedIn',
        morningRestrictedViolated: false,
        nightRestrictedViolated: false,
        date: threeDaysAgo,
      },
    ],
    commitments: [
      {
        id: 'c-1',
        name: 'Aditya Engineering College (CSE Department)',
        type: 'College',
        startTime: '08:45',
        endTime: '15:30',
        days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        startDate: '2026-06-15',
        status: 'active',
      },
      {
        id: 'c-2',
        name: 'AI Engineering Virtual Training',
        type: 'Training',
        startTime: '16:30',
        endTime: '17:30',
        days: ['Tuesday', 'Thursday'],
        startDate: '2026-09-01',
        status: 'active',
      },
    ],
    attendanceRecords: [
      {
        id: 'att-1',
        commitmentId: 'c-1',
        date: today,
        status: 'Attended',
        notes: 'Attended all lectures & DBMS practical lab.',
      },
      {
        id: 'att-2',
        commitmentId: 'c-1',
        date: yesterday,
        status: 'Attended',
      },
      {
        id: 'att-3',
        commitmentId: 'c-1',
        date: twoDaysAgo,
        status: 'Attended',
      },
      {
        id: 'att-4',
        commitmentId: 'c-1',
        date: threeDaysAgo,
        status: 'Attended',
      },
      {
        id: 'att-5',
        commitmentId: 'c-1',
        date: fourDaysAgo,
        status: 'Attended',
      },
      {
        id: 'att-6',
        commitmentId: 'c-1',
        date: fiveDaysAgo,
        status: 'Leave',
        notes: 'Sick leave granted.',
      },
    ],
    customFields: [
      {
        id: 'cf-1',
        name: 'Reading Books',
        target: 30,
        unit: 'mins',
        frequency: 'daily',
        description: 'Non-fiction & computer science books',
      },
      {
        id: 'cf-2',
        name: 'Meditation & Breathwork',
        target: 15,
        unit: 'mins',
        frequency: 'daily',
        description: 'Morning mindfulness session',
      },
    ],
    customFieldLogs: [
      {
        id: 'cfl-1',
        fieldId: 'cf-1',
        value: 30,
        date: today,
        notes: 'Read Atomic Habits chapter 4 & 5',
      },
      {
        id: 'cfl-2',
        fieldId: 'cf-2',
        value: 15,
        date: today,
        notes: 'Morning breath focus',
      },
      {
        id: 'cfl-3',
        fieldId: 'cf-1',
        value: 20,
        date: yesterday,
      },
    ],
    chatHistory: [
      {
        id: 'msg-1',
        role: 'assistant',
        content:
          "Namaste Himavanth! I am your LifeForge central brain. Today your college was scheduled until 3:30 PM, your workout is completed, and you've logged 2.5 hours of DBMS study. How can I assist you with your schedule or tracking right now?",
        timestamp: `${today}T17:00:00Z`,
        dynamicQuestions: [
          'Did you complete your planned study session today? (Please answer honestly.)',
          'How confident do you feel about the DBMS topic you studied today?',
        ],
      },
    ],
  };
}
